### ISSUE TITLE
Ensure PHP 7.4 compatibility

### ISSUE THREAD

**Issue by ohader** [TYPO3/phar-stream-wrapper#49]
PR #48 started to add compatibility for PHP 7.4 (snapshot), however there are a couple of tests that still fail for 7.4, see https://travis-ci.org/TYPO3/phar-stream-wrapper/builds/570805048

This might be related to current beta state - anyway it's worth taking a closer look...

**Comment by alexpott** [comment]
I think we need to bump the PHPUnit version - see https://github.com/sebastianbergmann/phpunit/pull/3765 - to at least 7.

**Comment by ohader** [comment]
Done for PR #52 (master) & PR #51 (v2). Seems to be unrelated to PhpUnit7..

**Comment by alexpott** [comment]
The current master and v2 are working great. New releases would be for PHP7.4 compat would be great. Thanks!

**Comment by ohader** [comment]
PHP 7.4 workarounds are removed in PR #53 & #54 
Thanks to @alexpott for pointing out that this was superfluous!

**Comment by ohader** [comment]
Done, new versions have been released
* https://github.com/TYPO3/phar-stream-wrapper/releases/tag/v3.1.3
* https://github.com/TYPO3/phar-stream-wrapper/releases/tag/v2.1.3
