### ISSUE TITLE
Version 2.2.2 not backwards compatible because of strict_types=1

### ISSUE THREAD

**Issue by oemmes** [TYPO3/phar-stream-wrapper#73]
Verison 2.2.2 seems to be published with the wrong sources.

Version 2.2.1 did not have strict_types=1 and no type annotations, version 2.2.2 now includes those which breaks compatibility for 2.2.x. In some projects we still have to use Typo3 7 which exits with an fatal error after update to 2.2.2.

Please publish a release with the correct sources for 2.2.x

**Comment by ohader** [comment]
Thanks for reporting this. I accidentally released from `master` branch via GitHub UI.
I've no recreated tag and release which points to https://github.com/TYPO3/phar-stream-wrapper/commit/cf7728109e0cab28da9ad357c3009e38d371116e in `v2` branch.
Sorry for any inconveniences this may have caused.
